-- https://gist.github.com/ereli/0c94ec74a1807aaa895b912766556cc2
CREATE SEQUENCE country_seq;

CREATE TABLE IF NOT EXISTS country (
    id int NOT NULL DEFAULT NEXTVAL ('country_seq'),
    iso char(2) NOT NULL UNIQUE,
    name varchar(80) NOT NULL,
    phonecode int NOT NULL,
    PRIMARY KEY (id)
  );
--
-- Dumping data for table `country`
--
INSERT INTO country (id, iso, name, phonecode) VALUES (1, 'AF', 'Afghanistan', 93);
INSERT INTO country (id, iso, name, phonecode) VALUES (2, 'AL', 'Albania', 355);
INSERT INTO country (id, iso, name, phonecode) VALUES (3, 'DZ', 'Algeria', 213);
INSERT INTO country (id, iso, name, phonecode) VALUES (4, 'AS', 'American Samoa', 1684);
INSERT INTO country (id, iso, name, phonecode) VALUES (5, 'AD', 'Andorra', 376);
INSERT INTO country (id, iso, name, phonecode) VALUES (6, 'AO', 'Angola', 244);
INSERT INTO country (id, iso, name, phonecode) VALUES (7, 'AI', 'Anguilla', 1264);
INSERT INTO country (id, iso, name, phonecode) VALUES (8, 'AQ', 'Antarctica', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (9, 'AG', 'Antigua and Barbuda', 1268);
INSERT INTO country (id, iso, name, phonecode) VALUES (10, 'AR', 'Argentina', 54);
INSERT INTO country (id, iso, name, phonecode) VALUES (11, 'AM', 'Armenia', 374);
INSERT INTO country (id, iso, name, phonecode) VALUES (12, 'AW', 'Aruba', 297);
INSERT INTO country (id, iso, name, phonecode) VALUES (13, 'AU', 'Australia', 61);
INSERT INTO country (id, iso, name, phonecode) VALUES (14, 'AT', 'Austria', 43);
INSERT INTO country (id, iso, name, phonecode) VALUES (15, 'AZ', 'Azerbaijan', 994);
INSERT INTO country (id, iso, name, phonecode) VALUES (16, 'BS', 'Bahamas', 1242);
INSERT INTO country (id, iso, name, phonecode) VALUES (17, 'BH', 'Bahrain', 973);
INSERT INTO country (id, iso, name, phonecode) VALUES (18, 'BD', 'Bangladesh', 880);
INSERT INTO country (id, iso, name, phonecode) VALUES (19, 'BB', 'Barbados', 1246);
INSERT INTO country (id, iso, name, phonecode) VALUES (20, 'BY', 'Belarus', 375);
INSERT INTO country (id, iso, name, phonecode) VALUES (21, 'BE', 'Belgium', 32);
INSERT INTO country (id, iso, name, phonecode) VALUES (22, 'BZ', 'Belize', 501);
INSERT INTO country (id, iso, name, phonecode) VALUES (23, 'BJ', 'Benin', 229);
INSERT INTO country (id, iso, name, phonecode) VALUES (24, 'BM', 'Bermuda', 1441);
INSERT INTO country (id, iso, name, phonecode) VALUES (25, 'BT', 'Bhutan', 975);
INSERT INTO country (id, iso, name, phonecode) VALUES (26, 'BO', 'Bolivia', 591);
INSERT INTO country (id, iso, name, phonecode) VALUES (27, 'BA', 'Bosnia and Herzegovina', 387);
INSERT INTO country (id, iso, name, phonecode) VALUES (28, 'BW', 'Botswana', 267);
INSERT INTO country (id, iso, name, phonecode) VALUES (29, 'BV', 'Bouvet Island', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (30, 'BR', 'Brazil', 55);
INSERT INTO country (id, iso, name, phonecode) VALUES (31, 'IO', 'British Indian Ocean Territory', 246);
INSERT INTO country (id, iso, name, phonecode) VALUES (32, 'BN', 'Brunei Darussalam', 673);
INSERT INTO country (id, iso, name, phonecode) VALUES (33, 'BG', 'Bulgaria', 359);
INSERT INTO country (id, iso, name, phonecode) VALUES (34, 'BF', 'Burkina Faso', 226);
INSERT INTO country (id, iso, name, phonecode) VALUES (35, 'BI', 'Burundi', 257);
INSERT INTO country (id, iso, name, phonecode) VALUES (36, 'KH', 'Cambodia', 855);
INSERT INTO country (id, iso, name, phonecode) VALUES (37, 'CM', 'Cameroon', 237);
INSERT INTO country (id, iso, name, phonecode) VALUES (38, 'CA', 'Canada', 1);
INSERT INTO country (id, iso, name, phonecode) VALUES (39, 'CV', 'Cape Verde', 238);
INSERT INTO country (id, iso, name, phonecode) VALUES (40, 'KY', 'Cayman Islands', 1345);
INSERT INTO country (id, iso, name, phonecode) VALUES (41, 'CF', 'Central African Republic', 236);
INSERT INTO country (id, iso, name, phonecode) VALUES (42, 'TD', 'Chad', 235);
INSERT INTO country (id, iso, name, phonecode) VALUES (43, 'CL', 'Chile', 56);
INSERT INTO country (id, iso, name, phonecode) VALUES (44, 'CN', 'China', 86);
INSERT INTO country (id, iso, name, phonecode) VALUES (45, 'CX', 'Christmas Island', 61);
INSERT INTO country (id, iso, name, phonecode) VALUES (46, 'CC', 'Cocos (Keeling) Islands', 672);
INSERT INTO country (id, iso, name, phonecode) VALUES (47, 'CO', 'Colombia', 57);
INSERT INTO country (id, iso, name, phonecode) VALUES (48, 'KM', 'Comoros', 269);
INSERT INTO country (id, iso, name, phonecode) VALUES (49, 'CG', 'Congo', 242);
INSERT INTO country (id, iso, name, phonecode) VALUES (50, 'CD', 'Congo, the Democratic Republic of the', 242);
INSERT INTO country (id, iso, name, phonecode) VALUES (51, 'CK', 'Cook Islands', 682);
INSERT INTO country (id, iso, name, phonecode) VALUES (52, 'CR', 'Costa Rica', 506);
INSERT INTO country (id, iso, name, phonecode) VALUES (53, 'CI', 'Cote D''Ivoire', 225);
INSERT INTO country (id, iso, name, phonecode) VALUES (54, 'HR', 'Croatia', 385);
INSERT INTO country (id, iso, name, phonecode) VALUES (55, 'CU', 'Cuba', 53);
INSERT INTO country (id, iso, name, phonecode) VALUES (56, 'CY', 'Cyprus', 357);
INSERT INTO country (id, iso, name, phonecode) VALUES (57, 'CZ', 'Czech Republic', 420);
INSERT INTO country (id, iso, name, phonecode) VALUES (58, 'DK', 'Denmark', 45);
INSERT INTO country (id, iso, name, phonecode) VALUES (59, 'DJ', 'Djibouti', 253);
INSERT INTO country (id, iso, name, phonecode) VALUES (60, 'DM', 'Dominica', 1767);
INSERT INTO country (id, iso, name, phonecode) VALUES (61, 'DO', 'Dominican Republic', 1809);
INSERT INTO country (id, iso, name, phonecode) VALUES (62, 'EC', 'Ecuador', 593);
INSERT INTO country (id, iso, name, phonecode) VALUES (63, 'EG', 'Egypt', 20);
INSERT INTO country (id, iso, name, phonecode) VALUES (64, 'SV', 'El Salvador', 503);
INSERT INTO country (id, iso, name, phonecode) VALUES (65, 'GQ', 'Equatorial Guinea', 240);
INSERT INTO country (id, iso, name, phonecode) VALUES (66, 'ER', 'Eritrea', 291);
INSERT INTO country (id, iso, name, phonecode) VALUES (67, 'EE', 'Estonia', 372);
INSERT INTO country (id, iso, name, phonecode) VALUES (68, 'ET', 'Ethiopia', 251);
INSERT INTO country (id, iso, name, phonecode) VALUES (69, 'FK', 'Falkland Islands (Malvinas)', 500);
INSERT INTO country (id, iso, name, phonecode) VALUES (70, 'FO', 'Faroe Islands', 298);
INSERT INTO country (id, iso, name, phonecode) VALUES (71, 'FJ', 'Fiji', 679);
INSERT INTO country (id, iso, name, phonecode) VALUES (72, 'FI', 'Finland', 358);
INSERT INTO country (id, iso, name, phonecode) VALUES (73, 'FR', 'France', 33);
INSERT INTO country (id, iso, name, phonecode) VALUES (74, 'GF', 'French Guiana', 594);
INSERT INTO country (id, iso, name, phonecode) VALUES (75, 'PF', 'French Polynesia', 689);
INSERT INTO country (id, iso, name, phonecode) VALUES (76, 'TF', 'French Southern Territories', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (77, 'GA', 'Gabon', 241);
INSERT INTO country (id, iso, name, phonecode) VALUES (78, 'GM', 'Gambia', 220);
INSERT INTO country (id, iso, name, phonecode) VALUES (79, 'GE', 'Georgia', 995);
INSERT INTO country (id, iso, name, phonecode) VALUES (80, 'DE', 'Germany', 49);
INSERT INTO country (id, iso, name, phonecode) VALUES (81, 'GH', 'Ghana', 233);
INSERT INTO country (id, iso, name, phonecode) VALUES (82, 'GI', 'Gibraltar', 350);
INSERT INTO country (id, iso, name, phonecode) VALUES (83, 'GR', 'Greece', 30);
INSERT INTO country (id, iso, name, phonecode) VALUES (84, 'GL', 'Greenland', 299);
INSERT INTO country (id, iso, name, phonecode) VALUES (85, 'GD', 'Grenada', 1473);
INSERT INTO country (id, iso, name, phonecode) VALUES (86, 'GP', 'Guadeloupe', 590);
INSERT INTO country (id, iso, name, phonecode) VALUES (87, 'GU', 'Guam', 1671);
INSERT INTO country (id, iso, name, phonecode) VALUES (88, 'GT', 'Guatemala', 502);
INSERT INTO country (id, iso, name, phonecode) VALUES (89, 'GN', 'Guinea', 224);
INSERT INTO country (id, iso, name, phonecode) VALUES (90, 'GW', 'Guinea-Bissau', 245);
INSERT INTO country (id, iso, name, phonecode) VALUES (91, 'GY', 'Guyana', 592);
INSERT INTO country (id, iso, name, phonecode) VALUES (92, 'HT', 'Haiti', 509);
INSERT INTO country (id, iso, name, phonecode) VALUES (93, 'HM', 'Heard Island and Mcdonald Islands', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (94, 'VA', 'Holy See (Vatican City State)', 39);
INSERT INTO country (id, iso, name, phonecode) VALUES (95, 'HN', 'Honduras', 504);
INSERT INTO country (id, iso, name, phonecode) VALUES (96, 'HK', 'Hong Kong', 852);
INSERT INTO country (id, iso, name, phonecode) VALUES (97, 'HU', 'Hungary', 36);
INSERT INTO country (id, iso, name, phonecode) VALUES (98, 'IS', 'Iceland', 354);
INSERT INTO country (id, iso, name, phonecode) VALUES (99, 'IN', 'India', 91);
INSERT INTO country (id, iso, name, phonecode) VALUES (100, 'ID', 'Indonesia', 62);
INSERT INTO country (id, iso, name, phonecode) VALUES (101, 'IR', 'Iran, Islamic Republic of', 98);
INSERT INTO country (id, iso, name, phonecode) VALUES (102, 'IQ', 'Iraq', 964);
INSERT INTO country (id, iso, name, phonecode) VALUES (103, 'IE', 'Ireland', 353);
INSERT INTO country (id, iso, name, phonecode) VALUES (104, 'IL', 'Israel', 972);
INSERT INTO country (id, iso, name, phonecode) VALUES (105, 'IT', 'Italy', 39);
INSERT INTO country (id, iso, name, phonecode) VALUES (106, 'JM', 'Jamaica', 1876);
INSERT INTO country (id, iso, name, phonecode) VALUES (107, 'JP', 'Japan', 81);
INSERT INTO country (id, iso, name, phonecode) VALUES (108, 'JO', 'Jordan', 962);
INSERT INTO country (id, iso, name, phonecode) VALUES (109, 'KZ', 'Kazakhstan', 7);
INSERT INTO country (id, iso, name, phonecode) VALUES (110, 'KE', 'Kenya', 254);
INSERT INTO country (id, iso, name, phonecode) VALUES (111, 'KI', 'Kiribati', 686);
INSERT INTO country (id, iso, name, phonecode) VALUES (112, 'KP', 'Korea, Democratic People''s Republic of', 850);
INSERT INTO country (id, iso, name, phonecode) VALUES (113, 'KR', 'Korea, Republic of', 82);
INSERT INTO country (id, iso, name, phonecode) VALUES (114, 'KW', 'Kuwait', 965);
INSERT INTO country (id, iso, name, phonecode) VALUES (115, 'KG', 'Kyrgyzstan', 996);
INSERT INTO country (id, iso, name, phonecode) VALUES (116, 'LA', 'Lao People''s Democratic Republic', 856);
INSERT INTO country (id, iso, name, phonecode) VALUES (117, 'LV', 'Latvia', 371);
INSERT INTO country (id, iso, name, phonecode) VALUES (118, 'LB', 'Lebanon', 961);
INSERT INTO country (id, iso, name, phonecode) VALUES (119, 'LS', 'Lesotho', 266);
INSERT INTO country (id, iso, name, phonecode) VALUES (120, 'LR', 'Liberia', 231);
INSERT INTO country (id, iso, name, phonecode) VALUES (121, 'LY', 'Libyan Arab Jamahiriya', 218);
INSERT INTO country (id, iso, name, phonecode) VALUES (122, 'LI', 'Liechtenstein', 423);
INSERT INTO country (id, iso, name, phonecode) VALUES (123, 'LT', 'Lithuania', 370);
INSERT INTO country (id, iso, name, phonecode) VALUES (124, 'LU', 'Luxembourg', 352);
INSERT INTO country (id, iso, name, phonecode) VALUES (125, 'MO', 'Macao', 853);
INSERT INTO country (id, iso, name, phonecode) VALUES (126, 'MK', 'Macedonia, the Former Yugoslav Republic of', 389);
INSERT INTO country (id, iso, name, phonecode) VALUES (127, 'MG', 'Madagascar', 261);
INSERT INTO country (id, iso, name, phonecode) VALUES (128, 'MW', 'Malawi', 265);
INSERT INTO country (id, iso, name, phonecode) VALUES (129, 'MY', 'Malaysia', 60);
INSERT INTO country (id, iso, name, phonecode) VALUES (130, 'MV', 'Maldives', 960);
INSERT INTO country (id, iso, name, phonecode) VALUES (131, 'ML', 'Mali', 223);
INSERT INTO country (id, iso, name, phonecode) VALUES (132, 'MT', 'Malta', 356);
INSERT INTO country (id, iso, name, phonecode) VALUES (133, 'MH', 'Marshall Islands', 692);
INSERT INTO country (id, iso, name, phonecode) VALUES (134, 'MQ', 'Martinique', 596);
INSERT INTO country (id, iso, name, phonecode) VALUES (135, 'MR', 'Mauritania', 222);
INSERT INTO country (id, iso, name, phonecode) VALUES (136, 'MU', 'Mauritius', 230);
INSERT INTO country (id, iso, name, phonecode) VALUES (137, 'YT', 'Mayotte', 269);
INSERT INTO country (id, iso, name, phonecode) VALUES (138, 'MX', 'Mexico', 52);
INSERT INTO country (id, iso, name, phonecode) VALUES (139, 'FM', 'Micronesia, Federated States of', 691);
INSERT INTO country (id, iso, name, phonecode) VALUES (140, 'MD', 'Moldova, Republic of', 373);
INSERT INTO country (id, iso, name, phonecode) VALUES (141, 'MC', 'Monaco', 377);
INSERT INTO country (id, iso, name, phonecode) VALUES (142, 'MN', 'Mongolia', 976);
INSERT INTO country (id, iso, name, phonecode) VALUES (143, 'MS', 'Montserrat', 1664);
INSERT INTO country (id, iso, name, phonecode) VALUES (144, 'MA', 'Morocco', 212);
INSERT INTO country (id, iso, name, phonecode) VALUES (145, 'MZ', 'Mozambique', 258);
INSERT INTO country (id, iso, name, phonecode) VALUES (146, 'MM', 'Myanmar', 95);
INSERT INTO country (id, iso, name, phonecode) VALUES (147, 'NA', 'Namibia', 264);
INSERT INTO country (id, iso, name, phonecode) VALUES (148, 'NR', 'Nauru', 674);
INSERT INTO country (id, iso, name, phonecode) VALUES (149, 'NP', 'Nepal', 977);
INSERT INTO country (id, iso, name, phonecode) VALUES (150, 'NL', 'Netherlands', 31);
INSERT INTO country (id, iso, name, phonecode) VALUES (151, 'AN', 'Netherlands Antilles', 599);
INSERT INTO country (id, iso, name, phonecode) VALUES (152, 'NC', 'New Caledonia', 687);
INSERT INTO country (id, iso, name, phonecode) VALUES (153, 'NZ', 'New Zealand', 64);
INSERT INTO country (id, iso, name, phonecode) VALUES (154, 'NI', 'Nicaragua', 505);
INSERT INTO country (id, iso, name, phonecode) VALUES (155, 'NE', 'Niger', 227);
INSERT INTO country (id, iso, name, phonecode) VALUES (156, 'NG', 'Nigeria', 234);
INSERT INTO country (id, iso, name, phonecode) VALUES (157, 'NU', 'Niue', 683);
INSERT INTO country (id, iso, name, phonecode) VALUES (158, 'NF', 'Norfolk Island', 672);
INSERT INTO country (id, iso, name, phonecode) VALUES (159, 'MP', 'Northern Mariana Islands', 1670);
INSERT INTO country (id, iso, name, phonecode) VALUES (160, 'NO', 'Norway', 47);
INSERT INTO country (id, iso, name, phonecode) VALUES (161, 'OM', 'Oman', 968);
INSERT INTO country (id, iso, name, phonecode) VALUES (162, 'PK', 'Pakistan', 92);
INSERT INTO country (id, iso, name, phonecode) VALUES (163, 'PW', 'Palau', 680);
INSERT INTO country (id, iso, name, phonecode) VALUES (164, 'PS', 'Palestinian Territory, Occupied', 970);
INSERT INTO country (id, iso, name, phonecode) VALUES (165, 'PA', 'Panama', 507);
INSERT INTO country (id, iso, name, phonecode) VALUES (166, 'PG', 'Papua New Guinea', 675);
INSERT INTO country (id, iso, name, phonecode) VALUES (167, 'PY', 'Paraguay', 595);
INSERT INTO country (id, iso, name, phonecode) VALUES (168, 'PE', 'Peru', 51);
INSERT INTO country (id, iso, name, phonecode) VALUES (169, 'PH', 'Philippines', 63);
INSERT INTO country (id, iso, name, phonecode) VALUES (170, 'PN', 'Pitcairn', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (171, 'PL', 'Poland', 48);
INSERT INTO country (id, iso, name, phonecode) VALUES (172, 'PT', 'Portugal', 351);
INSERT INTO country (id, iso, name, phonecode) VALUES (173, 'PR', 'Puerto Rico', 1787);
INSERT INTO country (id, iso, name, phonecode) VALUES (174, 'QA', 'Qatar', 974);
INSERT INTO country (id, iso, name, phonecode) VALUES (175, 'RE', 'Reunion', 262);
INSERT INTO country (id, iso, name, phonecode) VALUES (176, 'RO', 'Romania', 40);
INSERT INTO country (id, iso, name, phonecode) VALUES (177, 'RU', 'Russian Federation', 70);
INSERT INTO country (id, iso, name, phonecode) VALUES (178, 'RW', 'Rwanda', 250);
INSERT INTO country (id, iso, name, phonecode) VALUES (179, 'SH', 'Saint Helena', 290);
INSERT INTO country (id, iso, name, phonecode) VALUES (180, 'KN', 'Saint Kitts and Nevis', 1869);
INSERT INTO country (id, iso, name, phonecode) VALUES (181, 'LC', 'Saint Lucia', 1758);
INSERT INTO country (id, iso, name, phonecode) VALUES (182, 'PM', 'Saint Pierre and Miquelon', 508);
INSERT INTO country (id, iso, name, phonecode) VALUES (183, 'VC', 'Saint Vincent and the Grenadines', 1784);
INSERT INTO country (id, iso, name, phonecode) VALUES (184, 'WS', 'Samoa', 684);
INSERT INTO country (id, iso, name, phonecode) VALUES (185, 'SM', 'San Marino', 378);
INSERT INTO country (id, iso, name, phonecode) VALUES (186, 'ST', 'Sao Tome and Principe', 239);
INSERT INTO country (id, iso, name, phonecode) VALUES (187, 'SA', 'Saudi Arabia', 966);
INSERT INTO country (id, iso, name, phonecode) VALUES (188, 'SN', 'Senegal', 221);
INSERT INTO country (id, iso, name, phonecode) VALUES (189, 'CS', 'Serbia and Montenegro', 381);
INSERT INTO country (id, iso, name, phonecode) VALUES (190, 'SC', 'Seychelles', 248);
INSERT INTO country (id, iso, name, phonecode) VALUES (191, 'SL', 'Sierra Leone', 232);
INSERT INTO country (id, iso, name, phonecode) VALUES (192, 'SG', 'Singapore', 65);
INSERT INTO country (id, iso, name, phonecode) VALUES (193, 'SK', 'Slovakia', 421);
INSERT INTO country (id, iso, name, phonecode) VALUES (194, 'SI', 'Slovenia', 386);
INSERT INTO country (id, iso, name, phonecode) VALUES (195, 'SB', 'Solomon Islands', 677);
INSERT INTO country (id, iso, name, phonecode) VALUES (196, 'SO', 'Somalia', 252);
INSERT INTO country (id, iso, name, phonecode) VALUES (197, 'ZA', 'South Africa', 27);
INSERT INTO country (id, iso, name, phonecode) VALUES (198, 'GS', 'South Georgia and the South Sandwich Islands', 0);
INSERT INTO country (id, iso, name, phonecode) VALUES (199, 'ES', 'Spain', 34);
INSERT INTO country (id, iso, name, phonecode) VALUES (200, 'LK', 'Sri Lanka', 94);
INSERT INTO country (id, iso, name, phonecode) VALUES (201, 'SD', 'Sudan', 249);
INSERT INTO country (id, iso, name, phonecode) VALUES (202, 'SR', 'Suriname', 597);
INSERT INTO country (id, iso, name, phonecode) VALUES (203, 'SJ', 'Svalbard and Jan Mayen', 47);
INSERT INTO country (id, iso, name, phonecode) VALUES (204, 'SZ', 'Swaziland', 268);
INSERT INTO country (id, iso, name, phonecode) VALUES (205, 'SE', 'Sweden', 46);
INSERT INTO country (id, iso, name, phonecode) VALUES (206, 'CH', 'Switzerland', 41);
INSERT INTO country (id, iso, name, phonecode) VALUES (207, 'SY', 'Syrian Arab Republic', 963);
INSERT INTO country (id, iso, name, phonecode) VALUES (208, 'TW', 'Taiwan, Province of China', 886);
INSERT INTO country (id, iso, name, phonecode) VALUES (209, 'TJ', 'Tajikistan', 992);
INSERT INTO country (id, iso, name, phonecode) VALUES (210, 'TZ', 'Tanzania, United Republic of', 255);
INSERT INTO country (id, iso, name, phonecode) VALUES (211, 'TH', 'Thailand', 66);
INSERT INTO country (id, iso, name, phonecode) VALUES (212, 'TL', 'Timor-Leste', 670);
INSERT INTO country (id, iso, name, phonecode) VALUES (213, 'TG', 'Togo', 228);
INSERT INTO country (id, iso, name, phonecode) VALUES (214, 'TK', 'Tokelau', 690);
INSERT INTO country (id, iso, name, phonecode) VALUES (215, 'TO', 'Tonga', 676);
INSERT INTO country (id, iso, name, phonecode) VALUES (216, 'TT', 'Trinidad and Tobago', 1868);
INSERT INTO country (id, iso, name, phonecode) VALUES (217, 'TN', 'Tunisia', 216);
INSERT INTO country (id, iso, name, phonecode) VALUES (218, 'TR', 'Turkey', 90);
INSERT INTO country (id, iso, name, phonecode) VALUES (219, 'TM', 'Turkmenistan', 7370);
INSERT INTO country (id, iso, name, phonecode) VALUES (220, 'TC', 'Turks and Caicos Islands', 1649);
INSERT INTO country (id, iso, name, phonecode) VALUES (221, 'TV', 'Tuvalu', 688);
INSERT INTO country (id, iso, name, phonecode) VALUES (222, 'UG', 'Uganda', 256);
INSERT INTO country (id, iso, name, phonecode) VALUES (223, 'UA', 'Ukraine', 380);
INSERT INTO country (id, iso, name, phonecode) VALUES (224, 'AE', 'United Arab Emirates', 971);
INSERT INTO country (id, iso, name, phonecode) VALUES (225, 'GB', 'United Kingdom', 44);
INSERT INTO country (id, iso, name, phonecode) VALUES (226, 'US', 'United States', 1);
INSERT INTO country (id, iso, name, phonecode) VALUES (227, 'UM', 'United States Minor Outlying Islands', 1);
INSERT INTO country (id, iso, name, phonecode) VALUES (228, 'UY', 'Uruguay', 598);
INSERT INTO country (id, iso, name, phonecode) VALUES (229, 'UZ', 'Uzbekistan', 998);
INSERT INTO country (id, iso, name, phonecode) VALUES (230, 'VU', 'Vanuatu', 678);
INSERT INTO country (id, iso, name, phonecode) VALUES (231, 'VE', 'Venezuela', 58);
INSERT INTO country (id, iso, name, phonecode) VALUES (232, 'VN', 'Viet Nam', 84);
INSERT INTO country (id, iso, name, phonecode) VALUES (233, 'VG', 'Virgin Islands, British', 1284);
INSERT INTO country (id, iso, name, phonecode) VALUES (234, 'VI', 'Virgin Islands, U.s.', 1340);
INSERT INTO country (id, iso, name, phonecode) VALUES (235, 'WF', 'Wallis and Futuna', 681);
INSERT INTO country (id, iso, name, phonecode) VALUES (236, 'EH', 'Western Sahara', 212);
INSERT INTO country (id, iso, name, phonecode) VALUES (237, 'YE', 'Yemen', 967);
INSERT INTO country (id, iso, name, phonecode) VALUES (238, 'ZM', 'Zambia', 260);
INSERT INTO country (id, iso, name, phonecode) VALUES (239, 'ZW', 'Zimbabwe', 263);
